ingress:
  enabled: true
  hosts: 
  - "${grafana_domain}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
  tls:
  - secretName: grafana-tls
    hosts:
      - ${grafana_domain}

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-server.prometheus.svc.cluster.local
     access: proxy
     isDefault: true

grafana.ini:
  server:
    root_url: https://${grafana_domain}
  auth.generic_oauth:
    enabled: true
    name: UAA
    client_id: grafana-client
    client_secret: abcd1234
    scopes: "openid roles uaa.user"
    auth_url: https://${uaa_domain}/oauth/authorize
    token_url: https://${uaa_domain}/oauth/token
    api_url: https://${uaa_domain}/userinfo
    allow_sign_up: true