externalURL: https://${harbor_domain}
expose:
  tls:
    secretName: wildcard-tls-secret
    notarySecretName: wildcard-tls-secret
  ingress:
    hosts:
      core: ${harbor_domain}
      notary: ${notary_domain}
    annotations:
      kubernetes.io/ingress.class: "nginx"