alertmanager:
  enabled: false
pushgateway:
  enabled: false

server:
  ingress:
    enabled: true
    hosts: 
    - "${prometheus_domain}"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/auth-signin: https://${prometheus_domain}/oauth2/start?rd=$request_uri
      nginx.ingress.kubernetes.io/auth-url: https://${prometheus_domain}/oauth2/auth
      kubernetes.io/tls-acme: "true"
    tls:
    - secretName: prometheus-tls
      hosts:
        - ${prometheus_domain}