apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: ${cluster_issuer}
  namespace: certmanager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nthomson@pivotal.io
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
        - name: clouddns
          clouddns:
            project: ${project_id}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: ${cluster_issuer_staging}
  namespace: certmanager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: nthomson@pivotal.io
    privateKeySecretRef:
      name: letsencrypt-staging
    dns01:
      providers:
        - name: clouddns
          clouddns:
            project: ${project_id}